pipeline {
    agent any //To run on different agent = agent { node { label 'agent1' } }
    stages {
        stage('init') {
            steps {
                sh ''' 
                ls -ltr
                cd terraform_code
                echo "Pwd is:"
                pwd
                terraform init
                '''
            } 
        }
        stage('Plan') {
            steps {
                sh'''
                cd terraform_code
                terraform plan
                '''
            }
        }
        stage('Artifactcreation') {
            steps {
                echo 'Creating of artifact'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploy1'
            }
        }

    }

        post {
            always {
                echo "I will run everytime"
            }

            success {
                echo "I will run only on success"
            }
            failure {
                echo "I will run only on failure"
            }
        }
    
} 