#almalinux is same as centos
FROM almalinux:8 
#Label is to give tags. Adds metadata to your image. You can add as many labels as you like, and using backslashes \ to split lines is good practice for readability.
LABEL course=devops \
      trainer=shiva \
      duration=100hrs  
Run yum install epel-release -y
Run yum install nginx -y
CMD ["nginx", "-g", "daemon off;"]
