#almalinux is same as centos
FROM almalinux:8 

#The below is the way to use entrypoint command
#ENTRYPOINT ["ping", "-c5", "facebook.com;"]

#For best results combine entrypoint with cmd
#Here if user is not giving any options cmd can supply arguments to entrypoint
CMD ["google.com"]
ENTRYPOINT ["ping", "-c5"]
