pipeline {
    agent any //To run on different agent = agent { node { label 'agent1' } }
    
    stages {

        stage('Unit Test') { 
            steps {
                echo 'Unit Testing done' 
            }
        }
        //Sonar-scanner command expects sonar-project.properties should be available otherwise you will get error
        stage('SonarScan') {
            steps {
                 dir('Jenkins/catalogue_pipeline'){
                 sh '/opt/sonar-scanner/bin/sonar-scanner'
            }
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploy1'
            }
        }
    }

        post {
            always {
                echo "I will run everytime"
            }

            success {
                echo "I will run only on success"
            }
            failure {
                echo "I will run only on failure"
            }
        }
    
} 