pipeline {
    agent any //To run on different agent = agent { node { label 'agent1' } }
    
    stages {
         stage('Install Dependencies') {
            steps {
             sh ''' 
            ls -ltr 
             cd Jenkins/catalogue_pipeline
                 npm install
                 npm audit fix
                 npm audit fix --force

                 pwd
            '''
             } 
     }
        stage('Unit Test') { 
            steps {
                echo 'Unit Testing done' 
            }
        }
        //Sonar-scanner command expects sonar-project.properties should be available otherwise you will get error
        stage('SonarScan') {
            steps {
                sh 'sonar-scanner'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploy1'
            }
        }
    }

        post {
            always {
                echo "I will run everytime"
            }

            success {
                echo "I will run only on success"
            }
            failure {
                echo "I will run only on failure"
            }
        }
    
} 