pipeline {
    agent any //To run on different agent = agent { node { label 'agent1' } }
    stages {
        stage('Build') {
            steps {
                echo 'Building'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing'
            }
        }
        stage('Artifactcreation') {
            steps {
                echo 'Creating of artifact'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploy'
            }
        }
    }
} 