#Arg is to supply variables at build time
#Arg variable before from will not work after from
ARG version=8
FROM almalinux:${version}   
#RUN echo "Hi the version is {version}" > /tmp/hello.txt

RUN useradd cyril
USER cyril
RUN echo "Hi Docker /" > /tmp/hello.txt

#Sets the current working directory to /tmp. This is similar to cd tmp/
WORKDIR /tmp

ARG course=abc
RUN echo "The course is ${course} " >> /tmp/hello.txt
 
#To use arg varaible in run time, use env variable

ENV course=${course}
RUN echo "The course is ${course} " >> /tmp/hello.txt
